[workspace]
authors = ["Claudius Kienle <claudius.kienle@tu-darmstadt.de>"]
channels = ["conda-forge"]
name = "lang-segment-anything"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
sam = "python api.py"

[dependencies]
python = ">=3.9,<3.12"
pytorch = ">=2.7.1,<3"
fastapi = ">=0.116.1,<0.117"
pillow = ">=11.3.0,<12"
matplotlib = ">=3.10.3,<4"

[pypi-dependencies]
# lang-sam = { git = "https://github.com/luca-medeiros/lang-segment-anything" }
# groundingdino = { git = "https://github.com/IDEA-Research/GroundingDINO.git" }
transformers = "*"
opencv-python = ">=4.11.0.86, <5"
